import { useMemo, useState } from "react";
import { A2uiSurface } from "@a2ui/react/v0_9";
import { MessageProcessor } from "@a2ui/web_core/v0_9";
import { createPdsCatalog, CATALOG_NAME } from "./pdsCatalog";

const SAMPLE = JSON.stringify(
  {
    a2ui: [
      {
        version: "v0.9",
        createSurface: { surfaceId: "main", catalogId: CATALOG_NAME },
      },
      {
        version: "v0.9",
        updateDataModel: {
          surfaceId: "main",
          path: "/",
          value: {
            shoes: [
              { name: "Sneaker", price: "$120" },
              { name: "Boot", price: "$150" },
              { name: "Loafer", price: "$100" },
            ],
          },
        },
      },
      {
        version: "v0.9",
        updateComponents: {
          surfaceId: "main",
          components: [
            {
              id: "root",
              component: "TileContainer",
              children: { path: "/shoes", componentId: "shoe-tile" },
            },
            {
              id: "shoe-tile",
              component: "Tilelet",
              title: { children: { path: "name" } },
              subtitle: { children: { path: "price" } },
            },
          ],
        },
      },
    ],
  },
  null,
  2
);

/** Pull the ordered A2UI messages out of whatever the user pasted. */
function extractMessages(parsed: any): any[] {
  let msgs: any[] = [];
  if (Array.isArray(parsed)) msgs = parsed;
  else if (Array.isArray(parsed?.a2ui)) msgs = parsed.a2ui;
  else if (parsed?.createSurface || parsed?.updateComponents || parsed?.updateDataModel)
    msgs = [parsed];
  else if (parsed?.result?.status?.message?.parts) {
    // Tolerate an A2A JSON-RPC envelope too.
    for (const p of parsed.result.status.message.parts) {
      if (p?.data) msgs.push(p.data);
    }
  }

  return msgs
    .filter((m) => m && (m.createSurface || m.updateComponents || m.updateDataModel))
    .map((m) => {
      const out = { version: "v0.9", ...m };
      // Point every surface at our registered pds catalog.
      if (out.createSurface) out.createSurface.catalogId = CATALOG_NAME;
      return out;
    })
    .sort((a, b) => (a.createSurface ? -1 : 0) - (b.createSurface ? -1 : 0));
}

export default function App() {
  const [text, setText] = useState(SAMPLE);
  const [error, setError] = useState<string | null>(null);
  const [surfaces, setSurfaces] = useState<any[]>([]);

  // One processor, holding our pds catalog.
  const processor = useMemo(() => {
    const proc = new MessageProcessor([createPdsCatalog()], () => {});
    proc.onSurfaceCreated((surface: any) => {
      setSurfaces((prev) => [...prev.filter((s) => s.id !== surface.id), surface]);
    });
    proc.onSurfaceDeleted((surfaceId: string) => {
      setSurfaces((prev) => prev.filter((s) => s.id !== surfaceId));
    });
    return proc;
  }, []);

  const clearSurfaces = () => {
    surfaces.forEach((s) => {
      try {
        processor.processMessages([{ version: "v0.9", deleteSurface: { surfaceId: s.id } }]);
      } catch {
        /* ignore */
      }
    });
    setSurfaces([]);
  };

  const render = () => {
    setError(null);
    clearSurfaces();
    if (!text.trim()) {
      setError("Paste some A2UI JSON first.");
      return;
    }
    let parsed: any;
    try {
      parsed = JSON.parse(text);
    } catch (e: any) {
      setError(`JSON parse error: ${e.message}`);
      return;
    }
    const messages = extractMessages(parsed);
    if (messages.length === 0) {
      setError("No A2UI messages found (expected createSurface / updateComponents / updateDataModel).");
      return;
    }
    try {
      processor.processMessages(messages);
    } catch (e: any) {
      setError(`Render error: ${e.message}`);
    }
  };

  return (
    <div className="app">
      <header className="topbar">
        <h1>A2UI Renderer</h1>
        <span className="sub">paste A2UI JSON → preview with @pds/core</span>
      </header>

      <div className="split">
        <section className="pane left">
          <div className="pane-head">
            <h2>A2UI JSON</h2>
            <div className="actions">
              <button className="btn primary" onClick={render}>
                Render ▶
              </button>
              <button className="btn" onClick={() => { setText(""); clearSurfaces(); setError(null); }}>
                Clear
              </button>
              <button className="btn" onClick={() => setText(SAMPLE)}>
                Load sample
              </button>
            </div>
          </div>
          <textarea
            className="editor"
            spellCheck={false}
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="Paste the A2UI JSON generated by your server (or any A2UI v0.9 JSON)…"
          />
          {error && <div className="error">{error}</div>}
        </section>

        <section className="pane right">
          <div className="pane-head">
            <h2>Preview</h2>
          </div>
          <div className="preview">
            {surfaces.length === 0 && (
              <div className="empty">Nothing rendered yet — paste JSON and hit <b>Render</b>.</div>
            )}
            {surfaces.map((surface) => (
              <div key={surface.id} className="surface">
                <A2uiSurface surface={surface} />
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
