/**
 * Generates, from `component-metadata.mjs`:
 *   - `dist/@pds/core/catalog.json`  — an A2UI-format component catalog
 *     (https://github.com/a2ui-project/a2ui), importable as
 *     `import catalog from "@pds/core/catalog.json"`.
 *   - `dist/@pds/core/schemas/`  — one zod schema file per component, plus a
 *     barrel `index.js`, importable as
 *     `import { ButtonSchema, BadgeSchema } from "@pds/core/schemas"`.
 *
 * Composite props (`badge`, `title`, `items`, …) carry nested schemas via
 * `$ref` into `$defs` so a consumer (e.g. an LLM) can read the exact shape of
 * a nested object or array element.
 *
 * Runs after the rollup + tsc build (which produces `dist/@pds/core`).
 */
import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { components, sharedDefs, catalogMeta } from './component-metadata.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, '../dist/@pds/core');
const SCHEMAS_DIR = resolve(OUT_DIR, 'schemas');

const A2UI_COMMON =
    'https://a2ui.org/specification/v0_9/common_types.json#/$defs';

const HEADER =
    '// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.';

// A prop's `ref` points to a component (→ `<name>Props` $def); `sharedRef`
// points to a reusable shape (→ `<name>` $def). Both map to a `<name>Schema`.
const refDefKey = (spec) =>
    spec.ref ? `${spec.ref}Props` : spec.sharedRef ? spec.sharedRef : null;
const refSchemaName = (spec) =>
    spec.ref ? `${spec.ref}Schema` : spec.sharedRef ? `${spec.sharedRef}Schema` : null;

// ---------------------------------------------------------------------------
// A2UI catalog
// ---------------------------------------------------------------------------

const enumValueType = (values) => {
    if (values.every((v) => typeof v === 'number')) return 'number';
    if (values.every((v) => typeof v === 'string')) return 'string';
    return undefined; // mixed → leave type unset, rely on enum
};

const a2uiProperty = (prop) => {
    const withDescription = (schema) =>
        prop.description ? { ...schema, description: prop.description } : schema;

    switch (prop.type) {
        case 'string':
            return withDescription({
                type: 'string',
                ...(prop.default !== undefined && { default: prop.default }),
            });
        case 'number':
            return withDescription({
                type: 'number',
                ...(prop.default !== undefined && { default: prop.default }),
            });
        case 'boolean':
            return withDescription({
                type: 'boolean',
                ...(prop.default !== undefined && { default: prop.default }),
            });
        case 'enum': {
            const t = enumValueType(prop.enum);
            return withDescription({
                ...(t && { type: t }),
                enum: prop.enum,
                ...(prop.default !== undefined && { default: prop.default }),
            });
        }
        case 'node':
            return withDescription({ $ref: `${A2UI_COMMON}/DynamicString` });
        case 'array': {
            const key = prop.of ? refDefKey(prop.of) : null;
            return withDescription({
                type: 'array',
                items: key ? { $ref: `#/$defs/${key}` } : { type: 'object' },
            });
        }
        case 'object':
        default: {
            const key = refDefKey(prop);
            return key
                ? withDescription({ $ref: `#/$defs/${key}` })
                : withDescription({ type: 'object' });
        }
    }
};

// Build the `{ properties, required }` for a list of props (no `component`).
const buildProps = (props) => {
    const properties = {};
    const required = [];
    for (const prop of props) {
        properties[prop.name] = a2uiProperty(prop);
        if (prop.required) required.push(prop.name);
    }
    return { properties, required };
};

const buildCatalog = () => {
    const componentEntries = {};
    const propDefs = {};

    for (const component of components) {
        const { properties, required } = buildProps(component.props);

        componentEntries[component.name] = {
            type: 'object',
            description: component.description,
            allOf: [
                { $ref: `${A2UI_COMMON}/ComponentCommon` },
                { $ref: '#/$defs/CatalogComponentCommon' },
                {
                    type: 'object',
                    properties: { component: { const: component.name }, ...properties },
                    required: ['component', ...required],
                },
            ],
            unevaluatedProperties: false,
        };

        propDefs[`${component.name}Props`] = {
            type: 'object',
            properties,
            ...(required.length && { required }),
        };
    }

    for (const def of sharedDefs) {
        if (def.oneOf) {
            propDefs[def.name] = {
                ...(def.description && { description: def.description }),
                oneOf: def.oneOf.map((variant) => {
                    const { properties, required } = buildProps(variant.props);
                    return {
                        type: 'object',
                        properties,
                        ...(required.length && { required }),
                    };
                }),
            };
        } else {
            const { properties, required } = buildProps(def.props);
            propDefs[def.name] = {
                ...(def.description && { description: def.description }),
                type: 'object',
                properties,
                ...(required.length && { required }),
            };
        }
    }

    return {
        ...catalogMeta,
        components: componentEntries,
        functions: {},
        $defs: {
            CatalogComponentCommon: {
                type: 'object',
                properties: {
                    weight: {
                        type: 'number',
                        description:
                            "The relative weight of this component within a Row or Column, similar to CSS 'flex-grow'.",
                    },
                },
            },
            ...propDefs,
        },
    };
};

// ---------------------------------------------------------------------------
// zod schemas (one file per component + barrel)
// ---------------------------------------------------------------------------

const zodEnum = (values) => {
    if (values.every((v) => typeof v === 'string')) {
        return `z.enum([${values.map((v) => JSON.stringify(v)).join(', ')}])`;
    }
    return `z.union([${values
        .map((v) => `z.literal(${JSON.stringify(v)})`)
        .join(', ')}])`;
};

const zodBase = (prop) => {
    switch (prop.type) {
        case 'string':
            return 'z.string()';
        case 'number':
            return 'z.number()';
        case 'boolean':
            return 'z.boolean()';
        case 'enum':
            return zodEnum(prop.enum);
        case 'node':
            return 'z.any()';
        case 'array': {
            const name = prop.of ? refSchemaName(prop.of) : null;
            return name ? `z.array(z.lazy(() => ${name}))` : 'z.array(z.any())';
        }
        case 'object':
        default: {
            const name = refSchemaName(prop);
            return name ? `z.lazy(() => ${name})` : 'z.record(z.string(), z.any())';
        }
    }
};

const zodProperty = (prop) => {
    let expr = zodBase(prop);
    if (prop.default !== undefined) {
        expr += `.default(${JSON.stringify(prop.default)})`;
    } else if (!prop.required) {
        expr += '.optional()';
    }
    if (prop.description) {
        expr += `.describe(${JSON.stringify(prop.description)})`;
    }
    return expr;
};

const zodObject = (props) => {
    const lines = ['z.object({'];
    for (const prop of props) {
        lines.push(`    ${JSON.stringify(prop.name)}: ${zodProperty(prop)},`);
    }
    lines.push('})');
    return lines.join('\n');
};

// Schema names referenced by a prop list (drives per-file imports).
const referencedSchemas = (props) => {
    const set = new Set();
    for (const prop of props) {
        if (prop.type === 'object') {
            const n = refSchemaName(prop);
            if (n) set.add(n);
        } else if (prop.type === 'array' && prop.of) {
            const n = refSchemaName(prop.of);
            if (n) set.add(n);
        }
    }
    return set;
};

const importLines = (schemaNames, selfName) =>
    [...schemaNames]
        .filter((name) => name !== selfName)
        .sort()
        .map((name) => `import { ${name} } from './${name.replace(/Schema$/, '')}.js';`);

const componentSchemaFile = (component) => {
    const schemaName = `${component.name}Schema`;
    return [
        HEADER,
        "import { z } from 'zod';",
        ...importLines(referencedSchemas(component.props), schemaName),
        '',
        `export const ${schemaName} = ${zodObject(component.props)};`,
        '',
    ].join('\n');
};

const sharedSchemaFile = (def) => {
    const schemaName = `${def.name}Schema`;
    let body;
    const refs = new Set();
    if (def.oneOf) {
        for (const v of def.oneOf)
            referencedSchemas(v.props).forEach((n) => refs.add(n));
        const variants = def.oneOf
            .map((v) => zodObject(v.props).replace(/\n/g, '\n    '))
            .join(',\n    ');
        body = `export const ${schemaName} = z.union([\n    ${variants},\n]);`;
    } else {
        referencedSchemas(def.props).forEach((n) => refs.add(n));
        body = `export const ${schemaName} = ${zodObject(def.props)};`;
    }
    return [
        HEADER,
        "import { z } from 'zod';",
        ...importLines(refs, schemaName),
        '',
        body,
        '',
    ].join('\n');
};

const schemaDts = (name, kind) =>
    [
        HEADER,
        "import { z } from 'zod';",
        '',
        `export declare const ${name}Schema: ${kind};`,
        '',
    ].join('\n');

const allSchemaNames = [
    ...components.map((c) => c.name),
    ...sharedDefs.map((d) => d.name),
].map((n) => `${n}Schema`);

const barrelJs = () => {
    const imports = allSchemaNames.map(
        (name) => `import { ${name} } from './${name.replace(/Schema$/, '')}.js';`,
    );
    const list = allSchemaNames.map((name) => `    ${name},`).join('\n');
    return [
        HEADER,
        ...imports,
        '',
        'export {',
        list,
        '};',
        '',
        'export const schemas = {',
        list,
        '};',
        '',
    ].join('\n');
};

const barrelDts = () => {
    const imports = allSchemaNames.map(
        (name) => `import { ${name} } from './${name.replace(/Schema$/, '')}';`,
    );
    const list = allSchemaNames.map((name) => `    ${name},`).join('\n');
    const typed = allSchemaNames
        .map((name) => `    ${name}: typeof ${name};`)
        .join('\n');
    return [
        HEADER,
        ...imports,
        '',
        'export {',
        list,
        '};',
        '',
        'export declare const schemas: {',
        typed,
        '};',
        '',
    ].join('\n');
};

// ---------------------------------------------------------------------------
// Emit
// ---------------------------------------------------------------------------

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
if (!existsSync(SCHEMAS_DIR)) mkdirSync(SCHEMAS_DIR, { recursive: true });

const catalog = buildCatalog();
writeFileSync(
    resolve(OUT_DIR, 'catalog.json'),
    `${JSON.stringify(catalog, null, 2)}\n`,
);

for (const component of components) {
    writeFileSync(
        resolve(SCHEMAS_DIR, `${component.name}.js`),
        componentSchemaFile(component),
    );
    writeFileSync(
        resolve(SCHEMAS_DIR, `${component.name}.d.ts`),
        schemaDts(component.name, 'z.ZodObject<z.ZodRawShape>'),
    );
}
for (const def of sharedDefs) {
    writeFileSync(resolve(SCHEMAS_DIR, `${def.name}.js`), sharedSchemaFile(def));
    writeFileSync(
        resolve(SCHEMAS_DIR, `${def.name}.d.ts`),
        schemaDts(def.name, 'z.ZodTypeAny'),
    );
}
writeFileSync(resolve(SCHEMAS_DIR, 'index.js'), barrelJs());
writeFileSync(resolve(SCHEMAS_DIR, 'index.d.ts'), barrelDts());

console.log(
    `✓ catalog.json (${components.length} components, ${sharedDefs.length} shared defs) + schemas/ (${
        components.length + sharedDefs.length
    } files + barrel) → dist/@pds/core`,
);
